### ISSUE TITLE
tournaments_show_sets broken

### ISSUE THREAD

**Issue by LuNoX** [PeterCat12/pysmash#22] opened 2016-11-15 18:54 UTC
With 1.2.4 you broke tournament_show_sets it now either raises a ResponseError or returns an empty list.

**Comment by PeterCat12** [comment] 2016-11-15 19:08
what tournament are you looking at? my tests are passing (they are not the most comprehensive however) and `smash.tournament_show_sets('hidden-bosses-4-0')` returns proper set information.

**Comment by LuNoX** [comment] 2016-11-15 19:14
I just took my test tourney `'lunox-api-test'` (which returned the empty list) and a couple from the smash.gg front page which returned the ResponseError:
- `'rlcs-season-2'
  `
- `'kombat-cup-week-4'`
- `'eu-rcs-week-7'`

**Comment by PeterCat12** [comment] 2016-11-15 19:22
will look at the others tonight hopefully but `kombat-cup-week-4`  does not have an event for `wii-u-singles` (the current default param for an event) and thus, the error. If the same reason applies to the other tournaments, I'm going to close this issue as it is ultimately a duplicate of https://github.com/PeterCat12/pysmash/issues/16 . 

As I said previously, I had initially made this lib for the smash4 community for a personal project I am working on. Selfish, I know, but hopefully I can accommodate your needs when I have time this weekend.

**Closed as completed** 2016-11-15 19:37 UTC
